### ISSUE TITLE
Dependency Generator generates tasks in every module

### ISSUE THREAD

**Issue by fajarnuha** [VMadalin/android-modular-architecture#17]
## Description

Dependency Generator generates tasks in every module resulting graph is generated in every module build, I think its better to keep it lean and generate task only on rootProject 

and also it'd be awesome if we could add custom generator task that has local module filter

## Basic Information

-   Device type:
-   OS version:
-   App version:

**Comment by VMadalin** [comment]
Thanks, @fajarnuha for your suggestion. My apologies for the delay but I don't dedicate to much time to the project in order to maintain it. In fact, you are right the problem is that the [Dependency Generator](https://github.com/vanniktech/gradle-dependency-graph-generator-plugin) is a gradle plugin and it's necessary to generate the graph dependency per each module and I used it in order to generate the screenshots module dependencies.

Of course, it's a good tool but for modular projects, I was forced to use the `0.6.0-SNAPSHOT` in order to make it work.
